version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running tests..."
      - npm test
