version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - echo "Installing dependencies..."
      - npm install
  testing:
    commands:
      - echo "Running tests..."
      - CI=true npm test
