version: 0.2

phases:
  install:
    commands:
      - cd frontend ; npm install
  pre_build:
    commands:
      - echo "Pre-build steps"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id EFEM3CXY407YT --paths "/*"
      
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build'
