version: 0.2

phases:
  # install:
  #   commands:
  #     - cd frontend ; npm install
  # pre_build:
  #   commands:
  #     - echo "Pre-build steps"
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build'
